services:
  db:
    image: postgres:17
    container_name: nerp-db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nerp-db
    ports:
      - "5433:5432"
